# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

def basicFrameworks
  pod 'SnapKit', '~> 5.0.0'
  pod 'SDWebImage', '~> 5.0'
end

target 'SparkRefactoring' do
  basicFrameworks

  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'

  pod 'SwiftLint'
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod "KeyboardObserver", '~> 2.1'

end

target 'VocaGame' do
  basicFrameworks
  pod 'RxSwift'
  pod 'RxCocoa'
end

target 'VocaSubsystem' do
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
end

target 'VocaDesignSystem' do
end
